INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME, STUDENT_PHONE, UPDATED_TIME) VALUES (1, 'Kunal','+9112345678',now());

INSERT INTO COURSE VALUES (1,1,'JAVA','SRI');
INSERT INTO COURSE VALUES (2,1,'SPRING','NIVAS');
INSERT INTO COURSE VALUES (3,1,'HIBERNATE','MANISH');

INSERT INTO EMAIL_DETAILS VALUES (1, 1, 'kunal@coursecube.com');
INSERT INTO EMAIL_DETAILS VALUES (2, 1, 'kunal2success@gmail.com');

--------------------

INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME, STUDENT_PHONE, UPDATED_TIME) VALUES (2, 'Raman','+9198765431',now());

INSERT INTO COURSE VALUES (4,2,'PYTHON','SRI');
INSERT INTO COURSE VALUES (5,2,'HADOOP','NIVAS');
INSERT INTO COURSE VALUES (6,2,'SPARK','DANDE');

INSERT INTO EMAIL_DETAILS VALUES (3, 2, 'raman@coursecube.com');
INSERT INTO EMAIL_DETAILS VALUES (4, 2, 'raman@gmail.com');